version: '2'
services:
  testrpc:
    image: dougvk/mydapp_testrpc
    command: bash -c "testrpc -h 0.0.0.0"
  truffle3:
    image: dougvk/truffle3:latest
    command: bash
    stdin_open: true
    tty: true
    volumes_from:
      - truffle3_vol
  truffle3_vol:
    image: busybox
    container_name: truffle_vol
    volumes:
      - ../:/app

volumes:
  truffle3_vol:
